added golang image and multi-ide dependencies
cdr/enterprise-images pull request #115
Opened 2021-11-25 13:38 UTC by mtm20176

Using the GoLand JetBrains does not include Golang rendering a poor experience.  Adding enterprise-golang in lieu of multieditor image, and paste multieditor dependencies in GoLand image for JetBrains IDEs to continue to work in Projector (browser)

2021-11-29 15:03 UTC, vapurrmaid requested changes
The `CentOS` image needs to use the correct dependencies, otherwise this looks good to me to patch the problem.

2021-11-29 15:03 UTC, vapurrmaid commented on images/goland/Dockerfile.centos
> +
```suggestion
# Packages required for multi-editor support
RUN yum update -y && yum install -y \
    openssl \
    libXtst \
    libXrender \
    fontconfig \
    libXi \
    gtk3 \
    libGL

```

2021-11-30 12:21 UTC, mtm20176 commented on images/goland/Dockerfile.centos
> +
good catch. thanks.

2021-11-30 15:13 UTC, vapurrmaid approved these changes

2021-11-30 15:13 UTC, vapurrmaid commented
Thanks for the fix/contrib @mtm20176 ! 🎊

2021-11-30 15:15 UTC, merged