Added CLion image
cdr/enterprise-images pull request #81
Opened 2021-06-17 05:39 UTC by ntimo

This MR adds the Jetbrains clion image since clion is supported by coder and there has not been an image for it yet.

Sources: 
- https://coder.com/docs/coder/v1.19/workspaces/editors#jetbrains-ides-in-the-browser
- https://www.jetbrains.com/de-de/clion/

2021-06-17 12:03 UTC, bpmct requested changes
I started requesting changes, but I realized the Dockerfile still downloads GoLand instead of CLion too, not just the docs. Is *there missing a commit @ntimo?

2021-06-17 12:03 UTC, bpmct commented on images/clion/README.md
> +[![Docker Pulls](https://img.shields.io/docker/pulls/codercom/enterprise-goland?label=codercom%2Fenterprise-goland)](https://hub.docker.com/r/codercom/enterprise-goland)
```suggestion
# Enterprise CLion

[![Docker Pulls](https://img.shields.io/docker/pulls/codercom/enterprise-clion?label=codercom%2Fenterprise-clion)](https://hub.docker.com/r/codercom/enterprise-clion)
```

2021-06-17 12:36 UTC, ntimo commented
@bpmct I fixed the commit sorry. Doing merge requests after waking up without Coffee is probably not that good of an idea :D But now it should be fine I guess.

2021-06-17 14:22 UTC, bpmct approved these changes

2021-06-23 20:38 UTC, jawnsy commented
Looks good, thanks for this and sorry about the delay reviewing!

2021-06-23 20:38 UTC, merged